services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile

    container_name: enterprise-ai-backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    restart: unless-stopped
